### ISSUE TITLE
Add new column for bytes processed

### ISSUE THREAD

**Issue by bendiktv2** [elementary-data/elementary#617] opened 2023-01-25 08:45 UTC
**Is your feature request related to a problem? Please describe.**
To increase visibility into which DBT models costs money when running against BigQuery, we would like to have a new column for how many bytes were processed/billed. This could also be present for test-runs, as a wrongly configured test could end up costing a lot of money. (e.g. a full table scan for not_null in a column)

**Describe the solution you'd like**
I would like to have a new column in the elementary-dataset for reporting how many bytes were billed on a model-run, similar to how `dbt_artifacts` has `fct_dbt__model_executions.bytes_affected` (https://brooklyn-data.github.io/dbt_artifacts/#!/model/model.dbt_artifacts.fct_dbt__model_executions)

It should also be visible in the Elementary HTML-report under "Model Runs" and "Test Runs"

**Describe alternatives you've considered**
- Parsing DBT-logs
- Parsing run-results.json
- Querying against BigQuery's Jobs-dataset/API
- Using dbt_artifacts in tandem with Elementary

**Additional context**
BigQuery's on-demand billing bills per byte processed, so having models that consume a lot on unnecessary data will end up costing more. This feature will enable us to e.g. monitor when we need to move from a table-materialization to an incremental-materialization.

**Would you be willing to contribute this feature?**
No.

**Comment by elongl** [comment] 2023-01-25 09:45
Sorry for the confusion, closing this as a duplicate of https://github.com/elementary-data/elementary/issues/420.

**Closed by elongl** 2023-01-25 09:45 UTC
Labels: Feature request 💡, Triage 👀
