### ISSUE TITLE
Elementary model information_schema_columns fails with error: Unity Catalog is not enabled

### ISSUE THREAD

**Issue by hamzamazhar** [elementary-data/elementary#1533] opened 2024-05-23 15:11 UTC
**Describe the bug**
When I run `dbt run -s elementary`, it fails for the model `information_schema_columns` with the exception `[UC_NOT_ENABLED]`. My databricks cluster doesn't have unity catalog, neither am I specifying the catalog option in the `profiles.yaml` file.

I tried:
- Switching databricks access mode to `No Isolation shared` but it still failed.
- Passing the field `catalog: null` in the `profiles.yaml` file but it still fails.

When I print the value of the `target.catalog` variable in the `elementary/macros/edr/metadata_collection/get_columns_from_information_schema.sql` macro, it shows `hive_metastore`, even though I am not setting the catalog anywhere in my project.

**To Reproduce**

1. Setup a DBT project with databricks adapter that doesn't have unity catalog.
2. Add elementary as a package and install it with `dbt deps`.
3. Run `dbt run -s elementary` and see the error.

**Expected behavior**
Elementary should detect that I am not using unity catalog, and skip this model.

**Screenshots**

**Environment (please complete the following information):**

- edr Version: 0.15.0
- dbt package Version: 1.7.8
- dbt-databricks: 1.7.13

**Comment by haritamar** [comment] 2024-05-27 11:28
Hi @hamzamazhar !
I believe that this issue is likely a duplicate of this one:

#1428

So I'm closing it in favor of keeping the discussion in one place.
FYI though - since version 0.15.1 we actually removed completely the `information_schema_columns` model so I recommend upgrading to it, it should resolve your issue.

**Closed by haritamar** 2024-05-27 11:28 UTC
Labels: Bug, Triage 👀
