### ISSUE TITLE
DBT Columns for source contains only column that have a description

### ISSUE THREAD

**Issue by olivierdet** [elementary-data/elementary#1668] opened 2024-08-12 12:35 UTC
**Describe the bug**
DBT columns for source only contains column that have a documentation

**To Reproduce**
1 - Define tables inside sources 
2 - Create 2 columns, one with description the other without 
Only the column with description will appear in dbt_columns

We have something like 
```yml
version: 2

sources:
    tables:
      - name: customer
        columns:
          - name: email
            description: Professional email
          - name: first_name
            meta:
              database_tags:
                data_classification: "level_2"
```

Email appear in dbt_columns, `first_name` not

**Expected behavior**

I would expect to have the 2 columns. 

**Environment (please complete the following information):**

- Elementary CLI (edr) version: 0.16.1
- Elementary dbt package version: 0.16.0
- dbt version you're using 1.8.5
- Data warehouse Snowflake, drivers 1.8.3

**Would you be willing to contribute a fix for this issue?**
Yes, I can help if needed, just don't know where it is located

**Comment by IDoneShaveIt** [comment] 2024-08-15 08:05
Hey @olivierdet, thanks for raising that up!
This is actually an intended behaviour that we have.
By default we only upload columns that have description, but we have a way to control it 🙂 

In order to upload all columns, you should set the var `upload_only_columns_with_descriptions: false`

**Comment by IDoneShaveIt** [comment] 2024-08-15 08:08
I am closing this issue 🙂 
Please let us know if you still have any questions / something is still not working for you 🙏🏻

**Closed by IDoneShaveIt** 2024-08-15 08:08 UTC
Labels: Bug, Triage 👀

**Comment by olivierdet** [comment] 2024-08-16 10:27
Thanks, it works. 
I don't find it anywhere in the documentation. Is it intended ?
